services:
  test:
    build:
      context: .
      target: test
    command: make test

  lint:
    build:
      context: .
      target: test
    command: make lint

  ci:
    build:
      context: .
      target: test
    command: sh -c "make lint && make test"
